# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0
name: polaris
channels:
  - conda-forge
dependencies:
  # Core dependencies (alphabetical order)
  # Essential packages required for running polaris
  - deepdiff
  - gitpython
  - hydra-core=1.3.2
  - loguru=0.7.3
  - lxml=6.0.0
  - matplotlib=3.10.0
  - networkx=3.4.2
  - numpy=2.2.3
  - onnx=1.17.0
  - openpyxl=3.1.5
  - pydantic=2.10.6
  - pyelftools=0.31
  - python=3.13.2
  - pyyaml=6.0.2
  - simpy=4.1.1
  - sphinx=8.2.1
  - sphinx-rtd-theme=3.0.1
  - yaml=0.2.5
