# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

name: RTL Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  rtl-tests:
    env:
      GIST_ID: 'c230835a5065366c13d3bbfb79f23bf6'
      GIST_TOKEN: ${{ secrets.POLARIS_GIST_TOKEN }}
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_REF: ${{ github.ref }}
      GITHUB_SHA: ${{ github.sha }}

    runs-on: tt-ubuntu-2204-large-stable
    strategy:
      max-parallel: 5

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Download required files from LFC
      id: lfcdownload
      uses: ./.github/actions/lfcdownload
      with:
        files: 'ext_rtl_test_data_set_jul27.tar.gz'

    - name: Setup mamba - developer
      id: setup-mamba
      uses: ./.github/actions/setup_mamba
      with:
        environment-file: envdev.yaml
        environment-name: poldevenv

    - name: Run RTL Tests
      id: run-rtl-tests
      continue-on-error: true
      run: | 
        set -o pipefail ; python tests/standalone/execute_test.py --tag jul27 --parallel 4 2>&1 | tee rtl_test_results.txt
        find __llk_out -mindepth 2 -maxdepth 2 -name "*.png" -exec mv {} __llk_out/ \; 2>/dev/null || true

    - name: Generate RTL Badges
      id: generate-rtl-badges
      if: steps.run-rtl-tests.outcome == 'success' || steps.run-rtl-tests.outcome == 'failure'
      run: |
        EXIT_CODE=${{ steps.run-rtl-tests.outcome == 'success' && '0' || '1' }}
        python tools/ci/rtl_scurve_badge.py \
          --runexitcode $EXIT_CODE \
          --repo $REPO_NAME \
          --gistid $GIST_ID \
          --input rtl_test_results.txt

    - name: Upload artifacts
      id: upload-artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dumps-rtl-tests
        path: |
           rtl_test_results.txt
           __llk_out/*.json
           __llk_out/*.csv
           __llk_out/*.png

    - id: check-if-some-step-failed
      name: CheckIfRTLTestsStepFailed
      if : steps.run-rtl-tests.outcome == 'failure'
      run: exit 1